//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication2.OrderService {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfString", Namespace="http://tempuri.org/OrderService", ItemName="string")]
    [System.SerializableAttribute()]
    public class ArrayOfString : System.Collections.Generic.List<string> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://tempuri.org/OrderService", ConfigurationName="OrderService.OrderServiceSoap")]
    public interface OrderServiceSoap {
        
        // CODEGEN: Generating message contract since element name shopname from namespace http://tempuri.org/OrderService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderService/GetAllBookInfoByCondition", ReplyAction="*")]
        WebApplication2.OrderService.GetAllBookInfoByConditionResponse GetAllBookInfoByCondition(WebApplication2.OrderService.GetAllBookInfoByConditionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderService/GetAllBookInfoByCondition", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.OrderService.GetAllBookInfoByConditionResponse> GetAllBookInfoByConditionAsync(WebApplication2.OrderService.GetAllBookInfoByConditionRequest request);
        
        // CODEGEN: Generating message contract since element name bookId from namespace http://tempuri.org/OrderService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderService/UpdateBookInfo", ReplyAction="*")]
        WebApplication2.OrderService.UpdateBookInfoResponse UpdateBookInfo(WebApplication2.OrderService.UpdateBookInfoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderService/UpdateBookInfo", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.OrderService.UpdateBookInfoResponse> UpdateBookInfoAsync(WebApplication2.OrderService.UpdateBookInfoRequest request);
        
        // CODEGEN: Generating message contract since element name shopname from namespace http://tempuri.org/OrderService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderService/GetGoodByShop", ReplyAction="*")]
        WebApplication2.OrderService.GetGoodByShopResponse GetGoodByShop(WebApplication2.OrderService.GetGoodByShopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderService/GetGoodByShop", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.OrderService.GetGoodByShopResponse> GetGoodByShopAsync(WebApplication2.OrderService.GetGoodByShopRequest request);
        
        // CODEGEN: Generating message contract since element name shopname from namespace http://tempuri.org/OrderService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderService/GetGoodInfoByShop", ReplyAction="*")]
        WebApplication2.OrderService.GetGoodInfoByShopResponse GetGoodInfoByShop(WebApplication2.OrderService.GetGoodInfoByShopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderService/GetGoodInfoByShop", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.OrderService.GetGoodInfoByShopResponse> GetGoodInfoByShopAsync(WebApplication2.OrderService.GetGoodInfoByShopRequest request);
        
        // CODEGEN: Generating message contract since element name shopname from namespace http://tempuri.org/OrderService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderService/GetHotGoodByShop", ReplyAction="*")]
        WebApplication2.OrderService.GetHotGoodByShopResponse GetHotGoodByShop(WebApplication2.OrderService.GetHotGoodByShopRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderService/GetHotGoodByShop", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.OrderService.GetHotGoodByShopResponse> GetHotGoodByShopAsync(WebApplication2.OrderService.GetHotGoodByShopRequest request);
        
        // CODEGEN: Generating message contract since element name time from namespace http://tempuri.org/OrderService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderService/GetBookTrendByGood", ReplyAction="*")]
        WebApplication2.OrderService.GetBookTrendByGoodResponse GetBookTrendByGood(WebApplication2.OrderService.GetBookTrendByGoodRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderService/GetBookTrendByGood", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.OrderService.GetBookTrendByGoodResponse> GetBookTrendByGoodAsync(WebApplication2.OrderService.GetBookTrendByGoodRequest request);
        
        // CODEGEN: Generating message contract since element name shopname from namespace http://tempuri.org/OrderService is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderService/GetSaleByCondition", ReplyAction="*")]
        WebApplication2.OrderService.GetSaleByConditionResponse GetSaleByCondition(WebApplication2.OrderService.GetSaleByConditionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/OrderService/GetSaleByCondition", ReplyAction="*")]
        System.Threading.Tasks.Task<WebApplication2.OrderService.GetSaleByConditionResponse> GetSaleByConditionAsync(WebApplication2.OrderService.GetSaleByConditionRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBookInfoByConditionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBookInfoByCondition", Namespace="http://tempuri.org/OrderService", Order=0)]
        public WebApplication2.OrderService.GetAllBookInfoByConditionRequestBody Body;
        
        public GetAllBookInfoByConditionRequest() {
        }
        
        public GetAllBookInfoByConditionRequest(WebApplication2.OrderService.GetAllBookInfoByConditionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/OrderService")]
    public partial class GetAllBookInfoByConditionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shopname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string time;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string goodName;
        
        public GetAllBookInfoByConditionRequestBody() {
        }
        
        public GetAllBookInfoByConditionRequestBody(string shopname, string time, string goodName) {
            this.shopname = shopname;
            this.time = time;
            this.goodName = goodName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllBookInfoByConditionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllBookInfoByConditionResponse", Namespace="http://tempuri.org/OrderService", Order=0)]
        public WebApplication2.OrderService.GetAllBookInfoByConditionResponseBody Body;
        
        public GetAllBookInfoByConditionResponse() {
        }
        
        public GetAllBookInfoByConditionResponse(WebApplication2.OrderService.GetAllBookInfoByConditionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/OrderService")]
    public partial class GetAllBookInfoByConditionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication2.OrderService.ArrayOfString GetAllBookInfoByConditionResult;
        
        public GetAllBookInfoByConditionResponseBody() {
        }
        
        public GetAllBookInfoByConditionResponseBody(WebApplication2.OrderService.ArrayOfString GetAllBookInfoByConditionResult) {
            this.GetAllBookInfoByConditionResult = GetAllBookInfoByConditionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBookInfoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBookInfo", Namespace="http://tempuri.org/OrderService", Order=0)]
        public WebApplication2.OrderService.UpdateBookInfoRequestBody Body;
        
        public UpdateBookInfoRequest() {
        }
        
        public UpdateBookInfoRequest(WebApplication2.OrderService.UpdateBookInfoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/OrderService")]
    public partial class UpdateBookInfoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string bookId;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string status;
        
        public UpdateBookInfoRequestBody() {
        }
        
        public UpdateBookInfoRequestBody(string bookId, string status) {
            this.bookId = bookId;
            this.status = status;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateBookInfoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateBookInfoResponse", Namespace="http://tempuri.org/OrderService", Order=0)]
        public WebApplication2.OrderService.UpdateBookInfoResponseBody Body;
        
        public UpdateBookInfoResponse() {
        }
        
        public UpdateBookInfoResponse(WebApplication2.OrderService.UpdateBookInfoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/OrderService")]
    public partial class UpdateBookInfoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateBookInfoResult;
        
        public UpdateBookInfoResponseBody() {
        }
        
        public UpdateBookInfoResponseBody(bool UpdateBookInfoResult) {
            this.UpdateBookInfoResult = UpdateBookInfoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodByShopRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodByShop", Namespace="http://tempuri.org/OrderService", Order=0)]
        public WebApplication2.OrderService.GetGoodByShopRequestBody Body;
        
        public GetGoodByShopRequest() {
        }
        
        public GetGoodByShopRequest(WebApplication2.OrderService.GetGoodByShopRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/OrderService")]
    public partial class GetGoodByShopRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shopname;
        
        public GetGoodByShopRequestBody() {
        }
        
        public GetGoodByShopRequestBody(string shopname) {
            this.shopname = shopname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodByShopResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodByShopResponse", Namespace="http://tempuri.org/OrderService", Order=0)]
        public WebApplication2.OrderService.GetGoodByShopResponseBody Body;
        
        public GetGoodByShopResponse() {
        }
        
        public GetGoodByShopResponse(WebApplication2.OrderService.GetGoodByShopResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/OrderService")]
    public partial class GetGoodByShopResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication2.OrderService.ArrayOfString GetGoodByShopResult;
        
        public GetGoodByShopResponseBody() {
        }
        
        public GetGoodByShopResponseBody(WebApplication2.OrderService.ArrayOfString GetGoodByShopResult) {
            this.GetGoodByShopResult = GetGoodByShopResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodInfoByShopRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodInfoByShop", Namespace="http://tempuri.org/OrderService", Order=0)]
        public WebApplication2.OrderService.GetGoodInfoByShopRequestBody Body;
        
        public GetGoodInfoByShopRequest() {
        }
        
        public GetGoodInfoByShopRequest(WebApplication2.OrderService.GetGoodInfoByShopRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/OrderService")]
    public partial class GetGoodInfoByShopRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shopname;
        
        public GetGoodInfoByShopRequestBody() {
        }
        
        public GetGoodInfoByShopRequestBody(string shopname) {
            this.shopname = shopname;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetGoodInfoByShopResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetGoodInfoByShopResponse", Namespace="http://tempuri.org/OrderService", Order=0)]
        public WebApplication2.OrderService.GetGoodInfoByShopResponseBody Body;
        
        public GetGoodInfoByShopResponse() {
        }
        
        public GetGoodInfoByShopResponse(WebApplication2.OrderService.GetGoodInfoByShopResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/OrderService")]
    public partial class GetGoodInfoByShopResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication2.OrderService.ArrayOfString GetGoodInfoByShopResult;
        
        public GetGoodInfoByShopResponseBody() {
        }
        
        public GetGoodInfoByShopResponseBody(WebApplication2.OrderService.ArrayOfString GetGoodInfoByShopResult) {
            this.GetGoodInfoByShopResult = GetGoodInfoByShopResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHotGoodByShopRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHotGoodByShop", Namespace="http://tempuri.org/OrderService", Order=0)]
        public WebApplication2.OrderService.GetHotGoodByShopRequestBody Body;
        
        public GetHotGoodByShopRequest() {
        }
        
        public GetHotGoodByShopRequest(WebApplication2.OrderService.GetHotGoodByShopRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/OrderService")]
    public partial class GetHotGoodByShopRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shopname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string time;
        
        public GetHotGoodByShopRequestBody() {
        }
        
        public GetHotGoodByShopRequestBody(string shopname, string time) {
            this.shopname = shopname;
            this.time = time;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetHotGoodByShopResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetHotGoodByShopResponse", Namespace="http://tempuri.org/OrderService", Order=0)]
        public WebApplication2.OrderService.GetHotGoodByShopResponseBody Body;
        
        public GetHotGoodByShopResponse() {
        }
        
        public GetHotGoodByShopResponse(WebApplication2.OrderService.GetHotGoodByShopResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/OrderService")]
    public partial class GetHotGoodByShopResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication2.OrderService.ArrayOfString GetHotGoodByShopResult;
        
        public GetHotGoodByShopResponseBody() {
        }
        
        public GetHotGoodByShopResponseBody(WebApplication2.OrderService.ArrayOfString GetHotGoodByShopResult) {
            this.GetHotGoodByShopResult = GetHotGoodByShopResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookTrendByGoodRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookTrendByGood", Namespace="http://tempuri.org/OrderService", Order=0)]
        public WebApplication2.OrderService.GetBookTrendByGoodRequestBody Body;
        
        public GetBookTrendByGoodRequest() {
        }
        
        public GetBookTrendByGoodRequest(WebApplication2.OrderService.GetBookTrendByGoodRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/OrderService")]
    public partial class GetBookTrendByGoodRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string time;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string goodId;
        
        public GetBookTrendByGoodRequestBody() {
        }
        
        public GetBookTrendByGoodRequestBody(string time, string goodId) {
            this.time = time;
            this.goodId = goodId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetBookTrendByGoodResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetBookTrendByGoodResponse", Namespace="http://tempuri.org/OrderService", Order=0)]
        public WebApplication2.OrderService.GetBookTrendByGoodResponseBody Body;
        
        public GetBookTrendByGoodResponse() {
        }
        
        public GetBookTrendByGoodResponse(WebApplication2.OrderService.GetBookTrendByGoodResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/OrderService")]
    public partial class GetBookTrendByGoodResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication2.OrderService.ArrayOfString GetBookTrendByGoodResult;
        
        public GetBookTrendByGoodResponseBody() {
        }
        
        public GetBookTrendByGoodResponseBody(WebApplication2.OrderService.ArrayOfString GetBookTrendByGoodResult) {
            this.GetBookTrendByGoodResult = GetBookTrendByGoodResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSaleByConditionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSaleByCondition", Namespace="http://tempuri.org/OrderService", Order=0)]
        public WebApplication2.OrderService.GetSaleByConditionRequestBody Body;
        
        public GetSaleByConditionRequest() {
        }
        
        public GetSaleByConditionRequest(WebApplication2.OrderService.GetSaleByConditionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/OrderService")]
    public partial class GetSaleByConditionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string shopname;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string time;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string condition;
        
        public GetSaleByConditionRequestBody() {
        }
        
        public GetSaleByConditionRequestBody(string shopname, string time, string condition) {
            this.shopname = shopname;
            this.time = time;
            this.condition = condition;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSaleByConditionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSaleByConditionResponse", Namespace="http://tempuri.org/OrderService", Order=0)]
        public WebApplication2.OrderService.GetSaleByConditionResponseBody Body;
        
        public GetSaleByConditionResponse() {
        }
        
        public GetSaleByConditionResponse(WebApplication2.OrderService.GetSaleByConditionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/OrderService")]
    public partial class GetSaleByConditionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WebApplication2.OrderService.ArrayOfString GetSaleByConditionResult;
        
        public GetSaleByConditionResponseBody() {
        }
        
        public GetSaleByConditionResponseBody(WebApplication2.OrderService.ArrayOfString GetSaleByConditionResult) {
            this.GetSaleByConditionResult = GetSaleByConditionResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderServiceSoapChannel : WebApplication2.OrderService.OrderServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceSoapClient : System.ServiceModel.ClientBase<WebApplication2.OrderService.OrderServiceSoap>, WebApplication2.OrderService.OrderServiceSoap {
        
        public OrderServiceSoapClient() {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.OrderService.GetAllBookInfoByConditionResponse WebApplication2.OrderService.OrderServiceSoap.GetAllBookInfoByCondition(WebApplication2.OrderService.GetAllBookInfoByConditionRequest request) {
            return base.Channel.GetAllBookInfoByCondition(request);
        }
        
        public WebApplication2.OrderService.ArrayOfString GetAllBookInfoByCondition(string shopname, string time, string goodName) {
            WebApplication2.OrderService.GetAllBookInfoByConditionRequest inValue = new WebApplication2.OrderService.GetAllBookInfoByConditionRequest();
            inValue.Body = new WebApplication2.OrderService.GetAllBookInfoByConditionRequestBody();
            inValue.Body.shopname = shopname;
            inValue.Body.time = time;
            inValue.Body.goodName = goodName;
            WebApplication2.OrderService.GetAllBookInfoByConditionResponse retVal = ((WebApplication2.OrderService.OrderServiceSoap)(this)).GetAllBookInfoByCondition(inValue);
            return retVal.Body.GetAllBookInfoByConditionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.OrderService.GetAllBookInfoByConditionResponse> WebApplication2.OrderService.OrderServiceSoap.GetAllBookInfoByConditionAsync(WebApplication2.OrderService.GetAllBookInfoByConditionRequest request) {
            return base.Channel.GetAllBookInfoByConditionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.OrderService.GetAllBookInfoByConditionResponse> GetAllBookInfoByConditionAsync(string shopname, string time, string goodName) {
            WebApplication2.OrderService.GetAllBookInfoByConditionRequest inValue = new WebApplication2.OrderService.GetAllBookInfoByConditionRequest();
            inValue.Body = new WebApplication2.OrderService.GetAllBookInfoByConditionRequestBody();
            inValue.Body.shopname = shopname;
            inValue.Body.time = time;
            inValue.Body.goodName = goodName;
            return ((WebApplication2.OrderService.OrderServiceSoap)(this)).GetAllBookInfoByConditionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.OrderService.UpdateBookInfoResponse WebApplication2.OrderService.OrderServiceSoap.UpdateBookInfo(WebApplication2.OrderService.UpdateBookInfoRequest request) {
            return base.Channel.UpdateBookInfo(request);
        }
        
        public bool UpdateBookInfo(string bookId, string status) {
            WebApplication2.OrderService.UpdateBookInfoRequest inValue = new WebApplication2.OrderService.UpdateBookInfoRequest();
            inValue.Body = new WebApplication2.OrderService.UpdateBookInfoRequestBody();
            inValue.Body.bookId = bookId;
            inValue.Body.status = status;
            WebApplication2.OrderService.UpdateBookInfoResponse retVal = ((WebApplication2.OrderService.OrderServiceSoap)(this)).UpdateBookInfo(inValue);
            return retVal.Body.UpdateBookInfoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.OrderService.UpdateBookInfoResponse> WebApplication2.OrderService.OrderServiceSoap.UpdateBookInfoAsync(WebApplication2.OrderService.UpdateBookInfoRequest request) {
            return base.Channel.UpdateBookInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.OrderService.UpdateBookInfoResponse> UpdateBookInfoAsync(string bookId, string status) {
            WebApplication2.OrderService.UpdateBookInfoRequest inValue = new WebApplication2.OrderService.UpdateBookInfoRequest();
            inValue.Body = new WebApplication2.OrderService.UpdateBookInfoRequestBody();
            inValue.Body.bookId = bookId;
            inValue.Body.status = status;
            return ((WebApplication2.OrderService.OrderServiceSoap)(this)).UpdateBookInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.OrderService.GetGoodByShopResponse WebApplication2.OrderService.OrderServiceSoap.GetGoodByShop(WebApplication2.OrderService.GetGoodByShopRequest request) {
            return base.Channel.GetGoodByShop(request);
        }
        
        public WebApplication2.OrderService.ArrayOfString GetGoodByShop(string shopname) {
            WebApplication2.OrderService.GetGoodByShopRequest inValue = new WebApplication2.OrderService.GetGoodByShopRequest();
            inValue.Body = new WebApplication2.OrderService.GetGoodByShopRequestBody();
            inValue.Body.shopname = shopname;
            WebApplication2.OrderService.GetGoodByShopResponse retVal = ((WebApplication2.OrderService.OrderServiceSoap)(this)).GetGoodByShop(inValue);
            return retVal.Body.GetGoodByShopResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.OrderService.GetGoodByShopResponse> WebApplication2.OrderService.OrderServiceSoap.GetGoodByShopAsync(WebApplication2.OrderService.GetGoodByShopRequest request) {
            return base.Channel.GetGoodByShopAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.OrderService.GetGoodByShopResponse> GetGoodByShopAsync(string shopname) {
            WebApplication2.OrderService.GetGoodByShopRequest inValue = new WebApplication2.OrderService.GetGoodByShopRequest();
            inValue.Body = new WebApplication2.OrderService.GetGoodByShopRequestBody();
            inValue.Body.shopname = shopname;
            return ((WebApplication2.OrderService.OrderServiceSoap)(this)).GetGoodByShopAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.OrderService.GetGoodInfoByShopResponse WebApplication2.OrderService.OrderServiceSoap.GetGoodInfoByShop(WebApplication2.OrderService.GetGoodInfoByShopRequest request) {
            return base.Channel.GetGoodInfoByShop(request);
        }
        
        public WebApplication2.OrderService.ArrayOfString GetGoodInfoByShop(string shopname) {
            WebApplication2.OrderService.GetGoodInfoByShopRequest inValue = new WebApplication2.OrderService.GetGoodInfoByShopRequest();
            inValue.Body = new WebApplication2.OrderService.GetGoodInfoByShopRequestBody();
            inValue.Body.shopname = shopname;
            WebApplication2.OrderService.GetGoodInfoByShopResponse retVal = ((WebApplication2.OrderService.OrderServiceSoap)(this)).GetGoodInfoByShop(inValue);
            return retVal.Body.GetGoodInfoByShopResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.OrderService.GetGoodInfoByShopResponse> WebApplication2.OrderService.OrderServiceSoap.GetGoodInfoByShopAsync(WebApplication2.OrderService.GetGoodInfoByShopRequest request) {
            return base.Channel.GetGoodInfoByShopAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.OrderService.GetGoodInfoByShopResponse> GetGoodInfoByShopAsync(string shopname) {
            WebApplication2.OrderService.GetGoodInfoByShopRequest inValue = new WebApplication2.OrderService.GetGoodInfoByShopRequest();
            inValue.Body = new WebApplication2.OrderService.GetGoodInfoByShopRequestBody();
            inValue.Body.shopname = shopname;
            return ((WebApplication2.OrderService.OrderServiceSoap)(this)).GetGoodInfoByShopAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.OrderService.GetHotGoodByShopResponse WebApplication2.OrderService.OrderServiceSoap.GetHotGoodByShop(WebApplication2.OrderService.GetHotGoodByShopRequest request) {
            return base.Channel.GetHotGoodByShop(request);
        }
        
        public WebApplication2.OrderService.ArrayOfString GetHotGoodByShop(string shopname, string time) {
            WebApplication2.OrderService.GetHotGoodByShopRequest inValue = new WebApplication2.OrderService.GetHotGoodByShopRequest();
            inValue.Body = new WebApplication2.OrderService.GetHotGoodByShopRequestBody();
            inValue.Body.shopname = shopname;
            inValue.Body.time = time;
            WebApplication2.OrderService.GetHotGoodByShopResponse retVal = ((WebApplication2.OrderService.OrderServiceSoap)(this)).GetHotGoodByShop(inValue);
            return retVal.Body.GetHotGoodByShopResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.OrderService.GetHotGoodByShopResponse> WebApplication2.OrderService.OrderServiceSoap.GetHotGoodByShopAsync(WebApplication2.OrderService.GetHotGoodByShopRequest request) {
            return base.Channel.GetHotGoodByShopAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.OrderService.GetHotGoodByShopResponse> GetHotGoodByShopAsync(string shopname, string time) {
            WebApplication2.OrderService.GetHotGoodByShopRequest inValue = new WebApplication2.OrderService.GetHotGoodByShopRequest();
            inValue.Body = new WebApplication2.OrderService.GetHotGoodByShopRequestBody();
            inValue.Body.shopname = shopname;
            inValue.Body.time = time;
            return ((WebApplication2.OrderService.OrderServiceSoap)(this)).GetHotGoodByShopAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.OrderService.GetBookTrendByGoodResponse WebApplication2.OrderService.OrderServiceSoap.GetBookTrendByGood(WebApplication2.OrderService.GetBookTrendByGoodRequest request) {
            return base.Channel.GetBookTrendByGood(request);
        }
        
        public WebApplication2.OrderService.ArrayOfString GetBookTrendByGood(string time, string goodId) {
            WebApplication2.OrderService.GetBookTrendByGoodRequest inValue = new WebApplication2.OrderService.GetBookTrendByGoodRequest();
            inValue.Body = new WebApplication2.OrderService.GetBookTrendByGoodRequestBody();
            inValue.Body.time = time;
            inValue.Body.goodId = goodId;
            WebApplication2.OrderService.GetBookTrendByGoodResponse retVal = ((WebApplication2.OrderService.OrderServiceSoap)(this)).GetBookTrendByGood(inValue);
            return retVal.Body.GetBookTrendByGoodResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.OrderService.GetBookTrendByGoodResponse> WebApplication2.OrderService.OrderServiceSoap.GetBookTrendByGoodAsync(WebApplication2.OrderService.GetBookTrendByGoodRequest request) {
            return base.Channel.GetBookTrendByGoodAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.OrderService.GetBookTrendByGoodResponse> GetBookTrendByGoodAsync(string time, string goodId) {
            WebApplication2.OrderService.GetBookTrendByGoodRequest inValue = new WebApplication2.OrderService.GetBookTrendByGoodRequest();
            inValue.Body = new WebApplication2.OrderService.GetBookTrendByGoodRequestBody();
            inValue.Body.time = time;
            inValue.Body.goodId = goodId;
            return ((WebApplication2.OrderService.OrderServiceSoap)(this)).GetBookTrendByGoodAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WebApplication2.OrderService.GetSaleByConditionResponse WebApplication2.OrderService.OrderServiceSoap.GetSaleByCondition(WebApplication2.OrderService.GetSaleByConditionRequest request) {
            return base.Channel.GetSaleByCondition(request);
        }
        
        public WebApplication2.OrderService.ArrayOfString GetSaleByCondition(string shopname, string time, string condition) {
            WebApplication2.OrderService.GetSaleByConditionRequest inValue = new WebApplication2.OrderService.GetSaleByConditionRequest();
            inValue.Body = new WebApplication2.OrderService.GetSaleByConditionRequestBody();
            inValue.Body.shopname = shopname;
            inValue.Body.time = time;
            inValue.Body.condition = condition;
            WebApplication2.OrderService.GetSaleByConditionResponse retVal = ((WebApplication2.OrderService.OrderServiceSoap)(this)).GetSaleByCondition(inValue);
            return retVal.Body.GetSaleByConditionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WebApplication2.OrderService.GetSaleByConditionResponse> WebApplication2.OrderService.OrderServiceSoap.GetSaleByConditionAsync(WebApplication2.OrderService.GetSaleByConditionRequest request) {
            return base.Channel.GetSaleByConditionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WebApplication2.OrderService.GetSaleByConditionResponse> GetSaleByConditionAsync(string shopname, string time, string condition) {
            WebApplication2.OrderService.GetSaleByConditionRequest inValue = new WebApplication2.OrderService.GetSaleByConditionRequest();
            inValue.Body = new WebApplication2.OrderService.GetSaleByConditionRequestBody();
            inValue.Body.shopname = shopname;
            inValue.Body.time = time;
            inValue.Body.condition = condition;
            return ((WebApplication2.OrderService.OrderServiceSoap)(this)).GetSaleByConditionAsync(inValue);
        }
    }
}
